# Generated by Django 5.1.5 on 2025-02-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problems',
            options={'managed': True},
        ),
    ]
