# Generated by Django 5.0.7 on 2025-01-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemComments',
        ),
    ]
