# Generated by Django 5.0.7 on 2025-01-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0002_delete_problemcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomments',
            name='solution',
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
        migrations.DeleteModel(
            name='ProductComments',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
