# Generated by Django 5.1.5 on 2025-02-06 15:27

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0003_add_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(db_index=True, editable=False, null=True),
        ),
    ]
