# Generated by Django 5.0.7 on 2025-02-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0003_remove_productcomments_solution_delete_purchases_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MixerItems',
        ),
        migrations.DeleteModel(
            name='Mixers',
        ),
    ]
